name: CI

on:
  push:
    branches: 
      - develop
      - feature/develop/task2
  pull_request:
    branches:
      - develop

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml, curl
          ini-values: post_max_size=256M, upload_max_filesize=256M

      - name: Install Dependencies
        run: composer install

      - name: Set Environment Variable for Tests
        run: echo "BASE_URL=http://localhost:8000/web2125Ki408Klymiuk09" >> $GITHUB_ENV

      - name: Start PHP Built-In Server
        run: |
          php -S localhost:8000 -t . > /dev/null 2>&1 &
          sleep 5

      - name: Run Unit Tests
        run: vendor/bin/phpunit --configuration phpunit.xml

      - name: Zip Site
        run: zip -r web2125Ki408Klymiuk09.zip .

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: web2125Ki408Klymiuk09
          path: web2125Ki408Klymiuk09.zip
